version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: no-baddies-server
    build:
      context: ./
      target: production
    image: no-baddies-server
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: asimthande
      DB_PASSWORD: new_password
      DB_NAME: no-baddies
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local